const fs = require("fs");
const path = require("path");

const newVocab = [
  // HOUSE / FLAT
  {
    id: "house-rooms-1",
    word: "living room, bedroom, bathroom, garden, garage, balcony, toilet",
    phonetic: "",
    meaning_en: "parts and areas of a house",
    meaning_vi: "phòng khách, phòng ngủ, phòng tắm, vườn, ga-ra, ban công, nhà vệ sinh",
    example_en: "My dream house has a large garden and a beautiful balcony.",
    example_vi: "Ngôi nhà mơ ước của tôi có một khu vườn rộng và một ban công đẹp.",
    usage_vi: "Từ vựng cơ bản để liệt kê các phòng không gian trong nhà.",
    speaking_sentence: "My house is quite big with a living room, two bedrooms, a bathroom, and a small garden.",
    topic: "house_flat",
    category: "Rooms",
    level: "Beginner"
  },
  {
    id: "house-spacious-2",
    word: "large, big, spacious",
    phonetic: "",
    meaning_en: "having plenty of space",
    meaning_vi: "rộng lớn, rộng rãi",
    example_en: "I really love the living room because it is very spacious and bright.",
    example_vi: "Tôi thực sự yêu thích phòng khách vì nó rất rộng rãi và sáng sủa.",
    usage_vi: "'Spacious' (rộng rãi) là tính từ B1/B2 rất ăn điểm, hay hơn 'big'.",
    speaking_sentence: "Currently, I live in a spacious flat in the center of the city.",
    topic: "house_flat",
    category: "Adj",
    level: "Intermediate"
  },
  {
    id: "house-quiet-peaceful-3",
    word: "quiet, peaceful",
    phonetic: "",
    meaning_en: "without much noise or disturbance",
    meaning_vi: "yên tĩnh, thanh bình",
    example_en: "My bedroom is quiet and peaceful, making it perfect for studying.",
    example_vi: "Phòng ngủ của tôi yên tĩnh và thanh bình, hoàn hảo cho việc học.",
    usage_vi: "Tính từ miêu tả không khí lý tưởng của một ngôi nhà/phòng.",
    speaking_sentence: "I like my room because the atmosphere is always quiet and peaceful.",
    topic: "house_flat",
    category: "Adj",
    level: "Intermediate"
  },
  {
    id: "house-pretty-4",
    word: "pretty, beautiful",
    phonetic: "",
    meaning_en: "pleasing to the eye",
    meaning_vi: "xinh xắn, đẹp",
    example_en: "She decorated her flat to look very pretty and cozy.",
    example_vi: "Cô ấy trang trí căn hộ của mình để trông rất xinh xắn và ấm cúng.",
    usage_vi: "Tính từ cơ bản khen ngợi vẻ đẹp ngoại hình căn nhà.",
    speaking_sentence: "It is a beautiful house painted in light blue.",
    topic: "house_flat",
    category: "Adj",
    level: "Beginner"
  },
  {
    id: "house-negative-adj-5",
    word: "stuffy (ngột ngạt), drafty (nhiều gió lùa), cramped (chật chội)",
    phonetic: "",
    meaning_en: "unpleasant room conditions",
    meaning_vi: "ngột ngạt, nhiều gió lùa, chật chội",
    example_en: "The old apartment was stuffy in summer and drafty in winter.",
    example_vi: "Căn hộ cũ ngột ngạt vào mùa hè và nhiều gió lùa vào mùa đông.",
    usage_vi: "Bộ 3 tính từ cực hay để chê bai không gian.",
    speaking_sentence: "I want to move out because my current room is small, stuffy, and cramped.",
    topic: "house_flat",
    category: "Adj",
    level: "Advanced"
  },
  {
    id: "house-furniture-6",
    word: "table, TV, sofa, bookshelf, bed, wardrobe",
    phonetic: "",
    meaning_en: "common household furniture items",
    meaning_vi: "bàn, TV, ghế sofa, giá sách, giường, tủ quần áo",
    example_en: "My bedroom is simply furnished with a bed, a wardrobe, and a bookshelf.",
    example_vi: "Phòng ngủ của tôi được trang bị đơn giản với một chiếc giường, một tủ quần áo và một giá sách.",
    usage_vi: "Liệt kê khi được hỏi 'What is inside your room?'.",
    speaking_sentence: "In my bedroom, there is a big bed, a modern TV, and a wooden wardrobe.",
    topic: "house_flat",
    category: "Furniture",
    level: "Beginner"
  },
  {
    id: "house-activities-7",
    word: "grow plants and flowers in the garden",
    phonetic: "",
    meaning_en: "cultivate flora outside the house",
    meaning_vi: "trồng cây và hoa trong vườn",
    example_en: "My mother loves to grow plants and beautiful flowers in the garden.",
    example_vi: "Mẹ tôi thích trồng cây và hoa đẹp trong khu vườn.",
    usage_vi: "Hành động liên quan đến khu vườn (Garden).",
    speaking_sentence: "In my free time, I often help my dad grow plants and flowers in our garden.",
    topic: "house_flat",
    category: "Activities",
    level: "Intermediate"
  },
  {
    id: "house-living-room-act-8",
    word: "read books, watch TV, welcome guests in the living room",
    phonetic: "",
    meaning_en: "doing leisure and social activities in the main room",
    meaning_vi: "đọc sách, xem TV, tiếp khách ở phòng khách",
    example_en: "We often watch TV and welcome guests in our spacious living room.",
    example_vi: "Chúng tôi thường xem TV và tiếp khách ở phòng khách rộng rãi của mình.",
    usage_vi: "Hành động gắn với phòng khách (Living room). Welcome guests (đón khách).",
    speaking_sentence: "The living room is where my family gathers to watch TV and welcome guests.",
    topic: "house_flat",
    category: "Activities",
    level: "Intermediate"
  },

  // TECHNOLOGY (Combining Machine & Technology Mindmaps)
  {
    id: "tech-perform-faster-1",
    word: "perform faster and more efficiently",
    phonetic: "",
    meaning_en: "do work with greater speed and effectiveness",
    meaning_vi: "thực hiện nhanh hơn và hiệu quả hơn",
    example_en: "Machines help workers perform their tasks faster and more efficiently.",
    example_vi: "Máy móc giúp công nhân hoàn thành nhiệm vụ nhanh chóng và hiệu quả hơn.",
    usage_vi: "Perform = hoạt động/làm việc. Efficiently = một cách hiệu quả.",
    speaking_sentence: "Without a doubt, computers help me perform my work faster and more efficiently.",
    topic: "technology",
    category: "Advantages",
    level: "Intermediate"
  },
  {
    id: "tech-less-social-2",
    word: "have less social interactions",
    phonetic: "",
    meaning_en: "communicate less with people in person",
    meaning_vi: "ít tương tác xã hội hơn",
    example_en: "People who use phones too much might have less social interactions.",
    example_vi: "Những người cắm mặt vào điện thoại quá nhiều có thể ít tương tác xã hội hơn.",
    usage_vi: "Social interactions (Giao tiếp/tương tác xã hội).",
    speaking_sentence: "One major problem is that modern people have less social interactions.",
    topic: "technology",
    category: "Disadvantages",
    level: "Intermediate"
  },
  {
    id: "tech-lazy-depend-3",
    word: "make people lazier -> depend too much on machines -> refuse to do tasks by hand",
    phonetic: "",
    meaning_en: "cause idleness leading to over-reliance and avoiding manual work",
    meaning_vi: "khiến con người lười biếng hơn -> quá phụ thuộc vào máy móc -> từ chối làm việc bằng tay",
    example_en: "Technology make people lazier because they depend too much on machines and refuse to do tasks by hand.",
    example_vi: "Công nghệ làm con người lười biếng vì họ quá phụ thuộc máy móc và không chịu tự làm việc bằng tay.",
    usage_vi: "Một chuỗi nhân quả hoàn hảo cho câu trả lời band B2/C1.",
    speaking_sentence: "In addition, machines make people lazier because we depend too much on them.",
    topic: "technology",
    category: "Disadvantages",
    level: "Advanced"
  },
  {
    id: "tech-unemployment-4",
    word: "increase the unemployment rate",
    phonetic: "",
    meaning_en: "cause more people to lose their jobs",
    meaning_vi: "làm tăng tỷ lệ thất nghiệp",
    example_en: "AI replacing human workers will increase the unemployment rate.",
    example_vi: "AI thay thế lao động con người sẽ làm tăng tỷ lệ thất nghiệp.",
    usage_vi: "The unemployment rate (Tỷ lệ thất nghiệp).",
    speaking_sentence: "Moreover, using too many robots can increase the unemployment rate in society.",
    topic: "technology",
    category: "Disadvantages",
    level: "Advanced"
  },
  {
    id: "tech-solutions-5",
    word: "join social activities: team building, picnic, party",
    phonetic: "",
    meaning_en: "participate in group events",
    meaning_vi: "tham gia các hoạt động xã hội: team building, dã ngoại, tiệc tùng",
    example_en: "To avoid screen addiction, joining social activities like picnics is necessary.",
    example_vi: "Để tránh nghiện thiết bị điện tử, tham gia hoạt động xã hội như dã ngoại là rất cần thiết.",
    usage_vi: "Giải pháp bù đắp cho việc 'less social interactions'.",
    speaking_sentence: "To solve this, people should join social activities like picnics and parties.",
    topic: "technology",
    category: "Solutions",
    level: "Intermediate"
  },
  {
    id: "tech-responsibility-6",
    word: "raise the sense of responsibility",
    phonetic: "",
    meaning_en: "increase accountability and awareness",
    meaning_vi: "đề cao tinh thần trách nhiệm",
    example_en: "We must raise the sense of responsibility among young internet users.",
    example_vi: "Chúng ta phải nâng cao tinh thần trách nhiệm của người sử dụng internet trẻ tuổi.",
    usage_vi: "The sense of responsibility (Ý thức trách nhiệm).",
    speaking_sentence: "Furthermore, the government needs to raise the sense of responsibility online.",
    topic: "technology",
    category: "Solutions",
    level: "Advanced"
  },
  {
    id: "tech-training-7",
    word: "take some programs or training courses to control modern machines",
    phonetic: "",
    meaning_en: "learn how to operate new technology",
    meaning_vi: "tham gia một số chương trình hoặc khóa đào tạo để điều khiển máy móc hiện đại",
    example_en: "Workers must take training courses to control modern machines.",
    example_vi: "Người lao động cần tham gia các khóa đào tạo để vận hành máy móc hiện đại.",
    usage_vi: "Take courses (tham gia khóa học).",
    speaking_sentence: "Workers should take some training courses to control modern machines effectively.",
    topic: "technology",
    category: "Solutions",
    level: "Advanced"
  },
  {
    id: "tech-update-8",
    word: "update themselves with the development of science and technology",
    phonetic: "",
    meaning_en: "stay informed about latest tech advancements",
    meaning_vi: "tự cập nhật với sự phát triển của khoa học công nghệ",
    example_en: "Everyone should update themselves with the development of science to not fall behind.",
    example_vi: "Mọi người phải liên tục bắt kịp sự tiến bộ khoa học để không bị tụt hậu.",
    usage_vi: "Update oneself with... (Cập nhật bản thân với...).",
    speaking_sentence: "Finally, people must update themselves with the rapid development of technology.",
    topic: "technology",
    category: "Solutions",
    level: "Advanced"
  },
  {
    id: "machine-learning-way-9",
    word: "be a good way of learning and getting information / learn online",
    phonetic: "",
    meaning_en: "be a solid method for education and data gathering",
    meaning_vi: "là một cách tốt để học tập và thu nhận thông tin / học trực tuyến",
    example_en: "Using a laptop is a good way of learning and getting information easily.",
    example_vi: "Sử dụng laptop là một cách tốt để học hỏi và lấy thông tin rất dễ dàng.",
    usage_vi: "A good way OF + V-ing.",
    speaking_sentence: "Connecting to the internet is a good way of learning and getting information.",
    topic: "technology",
    category: "Advantages",
    level: "Intermediate"
  },
  {
    id: "machine-learning-details-10",
    word: "read newspapers online / download lots of information",
    phonetic: "",
    meaning_en: "consume digital news and acquire massive data",
    meaning_vi: "đọc báo mạng / tải về nhiều tài liệu",
    example_en: "Many people prefer to read newspapers online and download lots of information.",
    example_vi: "Nhiều người thích đọc báo trực tuyến và sao lưu về vô số tài liệu.",
    usage_vi: "Làm rõ luận điểm cho 'a good way of learning...'.",
    speaking_sentence: "For example, students can easily read newspapers online and download lots of information.",
    topic: "technology",
    category: "Advantages",
    level: "Beginner"
  },
  {
    id: "machine-work-study-11",
    word: "be convenient for work, study -> work faster and more efficiently",
    phonetic: "",
    meaning_en: "be useful for assignments prompting quicker results",
    meaning_vi: "tiện lợi cho công việc và học tập -> làm việc nhanh hơn và hiệu quả hơn",
    example_en: "Computers are very convenient for work and study because they help us work faster.",
    example_vi: "Máy tính tiện lợi cho công việc và học thuật vì chúng tăng tốc quá trình làm việc.",
    usage_vi: "Convenient FOR something.",
    speaking_sentence: "Modern machines are extremely convenient for work because we can work much faster.",
    topic: "technology",
    category: "Advantages",
    level: "Intermediate"
  },
  {
    id: "machine-tasks-12",
    word: "typing, printing documents, storing data",
    phonetic: "",
    meaning_en: "inputting text, producing hard copies, saving files",
    meaning_vi: "đánh máy, in ấn tài liệu, lưu trữ dữ liệu",
    example_en: "A computer is essential for typing, printing documents, and storing data safely.",
    example_vi: "Máy tính là cần thiết cho việc gõ văn bản, in ấn và lưu file an toàn.",
    usage_vi: "Liệt kê các tính năng văn phòng cơ bản.",
    speaking_sentence: "Specifically, computers are useful for typing, printing documents, and storing data.",
    topic: "technology",
    category: "Advantages",
    level: "Intermediate"
  },
  {
    id: "machine-entertain-13",
    word: "be a good way to entertain",
    phonetic: "",
    meaning_en: "be a great method for amusement",
    meaning_vi: "là một cách tốt để giải trí",
    example_en: "Watching YouTube is a good way to entertain after a stressful day.",
    example_vi: "Xem YouTube là tiện ích hay để giải tỏa căng thẳng sau một ngày áp lực.",
    usage_vi: "A good way TO + V (hoặc OF + V-ing).",
    speaking_sentence: "Besides working, a laptop can be a very good way to entertain.",
    topic: "technology",
    category: "Advantages",
    level: "Intermediate"
  },
  {
    id: "machine-entertain-details-14",
    word: "play games, listen to music, watch movies / join forums, Facebook groups to share ideas",
    phonetic: "",
    meaning_en: "engage in digital leisure and socialize online",
    meaning_vi: "chơi game, nghe nhạc, xem phim / tham gia diễn đàn, hội nhóm Facebook để chia sẻ ý tưởng",
    example_en: "I use my phone to play games, watch movies, and join Facebook groups.",
    example_vi: "Tôi dùng điện thoại để chơi game, coi phim và vào các hội nhóm trên mạng xã hội Facebook.",
    usage_vi: "Các hoạt động giải trí trên mạng cực kỳ phổ biến.",
    speaking_sentence: "After work, I usually play games and join Facebook groups to share ideas.",
    topic: "technology",
    category: "Advantages",
    level: "Beginner"
  },

  // LEARNING FOREIGN LANGUAGES
  {
    id: "lang-learn-info-1",
    word: "helps us learn and get information in the world -> many books are written in English",
    phonetic: "",
    meaning_en: "assist in global learning because numerous materials use English",
    meaning_vi: "giúp chúng ta học và lấy thông tin trên thế giới -> nhiều sách được viết bằng tiếng Anh",
    example_en: "English helps us learn and get information because many books are written in English.",
    example_vi: "Tiếng Anh cho phép chúng ta tìm kiếm thông tin bởi vì rất nhiều đầu sách được xuất bản bằng Anh ngữ.",
    usage_vi: "Cấu trúc Help sb V. Dẫn chứng rất thuyết phục để giải thích tầm quan trọng của Tiếng Anh.",
    speaking_sentence: "Firstly, learning English helps us learn and get information in the world easily.",
    topic: "languages",
    category: "Benefits",
    level: "Intermediate"
  },
  {
    id: "lang-confident-travel-2",
    word: "helps us feel more confident when travelling abroad",
    phonetic: "",
    meaning_en: "boost self-assurance during international trips",
    meaning_vi: "giúp chúng ta cảm thấy tự tin hơn khi đi du lịch nước ngoài",
    example_en: "Speaking French helps us feel more confident when travelling abroad to Paris.",
    example_vi: "Nói tiếng Pháp giúp ta thấy mạnh dạn hơn khi sang tận Paris du ngoạn.",
    usage_vi: "Confident (tự tin). Travel abroad (du lịch quốc tế).",
    speaking_sentence: "Secondly, a foreign language definitely helps us feel more confident when travelling abroad.",
    topic: "languages",
    category: "Benefits",
    level: "Intermediate"
  },
  {
    id: "lang-talk-foreigners-3",
    word: "talk easily with foreigners",
    phonetic: "",
    meaning_en: "converse smoothly with people from other countries",
    meaning_vi: "nói chuyện dễ dàng với người nước ngoài",
    example_en: "If you know English, you can talk easily with foreigners anywhere.",
    example_vi: "Nếu biết Anh văn, bạn có thể dễ dàng tâm tình với người gốc ngoại ở bất kì đâu.",
    usage_vi: "Adv 'easily' ghép sau động từ talk.",
    speaking_sentence: "This is because we can talk easily with foreigners to ask for directions.",
    topic: "languages",
    category: "Benefits",
    level: "Beginner"
  },
  {
    id: "lang-no-interpreter-4",
    word: "work and do business without an interpreter",
    phonetic: "",
    meaning_en: "conduct commerce unassisted by translators",
    meaning_vi: "làm việc và kinh doanh mà không cần phiên dịch viên",
    example_en: "Fluency allows managers to work and do business without an interpreter.",
    example_vi: "Sự lưu loát cho phép các sếp ký hợp đồng mà chẳng cần mướn người phiên dịch.",
    usage_vi: "An interpreter (phiên dịch viên nói). Khác với translator (viết).",
    speaking_sentence: "In addition, professionals can work and do business without an interpreter.",
    topic: "languages",
    category: "Benefits",
    level: "Advanced"
  },
  {
    id: "lang-learn-culture-5",
    word: "learn more about that country -> culture, people, society, customs and traditions",
    phonetic: "",
    meaning_en: "discover a nation's heritage and populace",
    meaning_vi: "tìm hiểu thêm về quốc gia đó -> văn hóa, con người, xã hội, phong tục và truyền thống",
    example_en: "Studying Korean helps you learn more about that country, its culture and customs.",
    example_vi: "Học ngoại ngữ Hàn hỗ trợ việc lĩnh hội tinh hoa văn hóa, con người và tập tục nước ấy.",
    usage_vi: "Customs and traditions (Phong tục và truyền thống) - Collocation luôn đi với nhau.",
    speaking_sentence: "It also allows us to learn more about a country's culture, people, and customs.",
    topic: "languages",
    category: "Benefits",
    level: "Intermediate"
  },
  {
    id: "lang-become-friends-6",
    word: "become friends with many people around the world",
    phonetic: "",
    meaning_en: "make international friendships",
    meaning_vi: "trở thành bạn bè với nhiều người trên khắp thế giới",
    example_en: "Language is a bridge to become friends with many people around the world.",
    example_vi: "Ngoại ngữ là nhịp cầu để kết bạn bốn phương.",
    usage_vi: "Become friends with (kết bạn với).",
    speaking_sentence: "Through language exchange apps, I become friends with many people around the world.",
    topic: "languages",
    category: "Benefits",
    level: "Beginner"
  },
  {
    id: "lang-open-door-7",
    word: "open a new door to the world",
    phonetic: "",
    meaning_en: "create vast new global opportunities",
    meaning_vi: "mở ra một cánh cửa mới ra thế giới",
    example_en: "Mastering English will literally open a new door to the world for your career.",
    example_vi: "Thành thạo Anh ngữ thực sự sẽ tạo ngã rẽ sự nghiệp dẫn ra thế giới.",
    usage_vi: "Thành ngữ (Idiom) tuyệt đẹp dùng làm câu kết (Conclusion).",
    speaking_sentence: "To conclude, mastering a foreign language can truly open a new door to the world.",
    topic: "languages",
    category: "Benefits",
    level: "Advanced"
  }
];

const vocabFilePath = path.join(__dirname, "src/data/vocabulary.ts");
let fileContent = fs.readFileSync(vocabFilePath, "utf8");

// Append new vocab to the array inside vocabulary.ts
let vocabString = newVocab.map(v => JSON.stringify(v, null, 4)).join(",\n  ") + "\n];\n";
fileContent = fileContent.replace(/\n\];\n/, ",\n  " + vocabString);

// Add "house_flat", "languages" to VSTEP_TOPICS if they don't exist
if (!fileContent.includes('"languages"')) {
    fileContent = fileContent.replace('["transport", "city", "countryside", "health", "environment", "hobbies", "job_study", "food", "technology"]', '["transport", "city", "countryside", "health", "environment", "hobbies", "job_study", "food", "technology", "house_flat", "languages"]');
}

fs.writeFileSync(vocabFilePath, fileContent);
console.log("Successfully injected " + newVocab.length + " items for House, Technology, Languages into vocabulary.ts!");
