const fs = require("fs");

const newVocab = [
  // ENVIRONMENT
  {
    id: "reuse-recycle-1",
    word: "reuse and recycle products",
    phonetic: "",
    meaning_en: "use items again and process waste",
    meaning_vi: "tái sử dụng và tái chế các sản phẩm",
    example_en: "We should reuse and recycle products to minimize waste.",
    example_vi: "Chúng ta nên tái sử dụng và tái chế sản phẩm để giảm thiểu rác thải.",
    usage_vi: "Động từ 'reuse' và 'recycle'. Thói quen tốt bảo vệ môi trường.",
    speaking_sentence: "A good habit is to reuse and recycle products everyday.",
    topic: "environment",
    category: "Good habits",
    level: "Intermediate"
  },
  {
    id: "consume-less-energy-2",
    word: "consume less energy / save energy",
    phonetic: "",
    meaning_en: "use a smaller amount of power",
    meaning_vi: "tiêu thụ ít năng lượng hơn / tiết kiệm năng lượng",
    example_en: "Turning off lights helps to consume less energy.",
    example_vi: "Tắt đèn giúp tiêu thụ ít năng lượng hơn.",
    usage_vi: "Cụm động từ 'consume energy' (tiêu thụ năng lượng).",
    speaking_sentence: "We must try to consume less energy to protect our earth.",
    topic: "environment",
    category: "Good habits",
    level: "Intermediate"
  },
  {
    id: "sort-trash-3",
    word: "sort trash",
    phonetic: "",
    meaning_en: "separate garbage into categories",
    meaning_vi: "phân loại rác",
    example_en: "It is important to sort trash into plastic and paper.",
    example_vi: "Phân loại rác thành nhựa và giấy là rất quan trọng.",
    usage_vi: "Collocation 'sort' (phân loại) + 'trash' (rác).",
    speaking_sentence: "At home, we usually sort trash before throwing it away.",
    topic: "environment",
    category: "Good habits",
    level: "Intermediate"
  },
  {
    id: "use-reusable-products-4",
    word: "use more reusable products",
    phonetic: "",
    meaning_en: "utilize items that can be used multiple times",
    meaning_vi: "sử dụng nhiều sản phẩm dùng lại được",
    example_en: "Shoppers should use more reusable products such as cloth bags.",
    example_vi: "Người mua sắm nên sử dụng nhiều sản phẩm có thể tái sử dụng hơn như túi vải.",
    usage_vi: "Tính từ 'reusable' bổ nghĩa cho 'products'.",
    speaking_sentence: "Instead of plastic, I prefer to use more reusable products.",
    topic: "environment",
    category: "Good habits",
    level: "Intermediate"
  },
  {
    id: "protect-long-term-5",
    word: "protect the environment in the long term",
    phonetic: "",
    meaning_en: "keep nature safe for a long period",
    meaning_vi: "bảo vệ môi trường về lâu dài",
    example_en: "These habits protect the environment in the long term.",
    example_vi: "Những thói quen này bảo vệ môi trường về lâu dài.",
    usage_vi: "Cụm trạng từ 'in the long term' (về thiết thực/lâu dài).",
    speaking_sentence: "These actions will surely protect the environment in the long term.",
    topic: "environment",
    category: "Benefits",
    level: "Intermediate"
  },
  {
    id: "conserve-natural-resources-6",
    word: "conserve natural resources",
    phonetic: "",
    meaning_en: "prevent the waste of natural materials",
    meaning_vi: "bảo tồn tài nguyên thiên nhiên",
    example_en: "Saving electricity helps to conserve natural resources.",
    example_vi: "Tiết kiệm điện giúp bảo tồn tài nguyên thiên nhiên.",
    usage_vi: "Collocation rất hay dùng (conserve natural resources).",
    speaking_sentence: "By planting trees, we can conserve natural resources effectively.",
    topic: "environment",
    category: "Benefits",
    level: "Intermediate"
  },
  {
    id: "reduce-levels-pollution-7",
    word: "reduce levels of pollution",
    phonetic: "",
    meaning_en: "lower the amount of contamination",
    meaning_vi: "giảm thiểu mức độ ô nhiễm",
    example_en: "Riding a bicycle can reduce levels of pollution in the city.",
    example_vi: "Đi xe đạp có thể giúp giảm ô nhiễm trong thành phố.",
    usage_vi: "Cụm danh từ 'levels of pollution' đi sau động từ 'reduce'.",
    speaking_sentence: "Electric vehicles are a great way to reduce levels of pollution.",
    topic: "environment",
    category: "Benefits",
    level: "Intermediate"
  },
  {
    id: "tackle-global-warming-8",
    word: "tackle some causes of global warming",
    phonetic: "",
    meaning_en: "deal with reasons behind the heating of the earth",
    meaning_vi: "giải quyết một số nguyên nhân của sự nóng lên toàn cầu",
    example_en: "Governments must tackle some causes of global warming.",
    example_vi: "Các chính phủ phải giải quyết một số nguyên nhân của biến đổi khí hậu.",
    usage_vi: "Động từ 'tackle' (giải quyết) nâng cao hơn 'solve'.",
    speaking_sentence: "It is crucial to tackle some causes of global warming sooner than later.",
    topic: "environment",
    category: "Benefits",
    level: "Advanced"
  },
  {
    id: "cause-climate-change-9",
    word: "cause global warming / climate change",
    phonetic: "",
    meaning_en: "make the earth steeper in temperature",
    meaning_vi: "gây ra sự nóng lên toàn cầu / biến đổi khí hậu",
    example_en: "Cutting down forests can cause global warming.",
    example_vi: "Phá rừng có thể gây ra hiện tượng nóng lên toàn cầu.",
    usage_vi: "Cause (v) gây ra + Danh từ.",
    speaking_sentence: "Unfortunately, factory emissions cause global warming and climate change.",
    topic: "environment",
    category: "Drawbacks",
    level: "Intermediate"
  },
  {
    id: "pollute-environment-10",
    word: "pollute the environment",
    phonetic: "",
    meaning_en: "make nature dirty and unsafe",
    meaning_vi: "gây ô nhiễm môi trường",
    example_en: "Plastic waste will severely pollute the environment.",
    example_vi: "Rác thải nhựa sẽ làm ô nhiễm môi trường nghiêm trọng.",
    usage_vi: "Động từ 'pollute' thay vì cụm 'make polluted'.",
    speaking_sentence: "People shouldn't throw garbage here because it will pollute the environment.",
    topic: "environment",
    category: "Drawbacks",
    level: "Intermediate"
  },
  {
    id: "exploit-natural-resources-11",
    word: "exploit natural resources",
    phonetic: "",
    meaning_en: "overuse materials from nature",
    meaning_vi: "khai thác (quá mức) tài nguyên thiên nhiên",
    example_en: "Big companies exploit natural resources to make more profits.",
    example_vi: "Các công ty lớn khai thác tài nguyên để kiếm nhiều lợi nhuận hơn.",
    usage_vi: "Động từ 'exploit' (khai thác/trục lợi).",
    speaking_sentence: "Another problem is that humans exploit natural resources too quickly.",
    topic: "environment",
    category: "Drawbacks",
    level: "Intermediate"
  },
  {
    id: "increase-greenhouse-emissions-12",
    word: "increase greenhouse gas emissions",
    phonetic: "",
    meaning_en: "raise the release of warming gases",
    meaning_vi: "làm tăng lượng khí thải nhà kính",
    example_en: "Too many cars increase greenhouse gas emissions.",
    example_vi: "Quá nhiều xe hơi làm tăng lượng khí thải nhà kính.",
    usage_vi: "Cụm danh từ chuyên ngành 'greenhouse gas emissions'. Rất tốt cho B1+.",
    speaking_sentence: "Industrial activities dangerously increase greenhouse gas emissions.",
    topic: "environment",
    category: "Drawbacks",
    level: "Advanced"
  },

  // HOBBIES
  {
    id: "free-time-activities-1",
    word: "free time activities / leisure activities",
    phonetic: "",
    meaning_en: "things done for enjoyment when not working",
    meaning_vi: "các hoạt động trong thời gian rảnh rỗi / giải trí",
    example_en: "My leisure activities include reading and swimming.",
    example_vi: "Hoạt động giải trí của tôi bao gồm đọc sách và bơi lội.",
    usage_vi: "Từ đồng nghĩa mạnh của 'hobbies'. Nên thay thế linh hoạt.",
    speaking_sentence: "In terms of leisure activities, I am really interested in sports.",
    topic: "hobbies",
    category: "Synonyms",
    level: "Intermediate"
  },
  {
    id: "types-of-hobbies-2",
    word: "listening to music, reading books, watching films",
    phonetic: "",
    meaning_en: "common indoor entertainment activities",
    meaning_vi: "nghe nhạc, đọc sách, xem phim",
    example_en: "I love indoor hobbies like reading books and watching films.",
    example_vi: "Tôi thích những sở thích trong nhà như đọc sách và xem phim.",
    usage_vi: "Liệt kê thói quen phổ biến.",
    speaking_sentence: "For example, listening to music or watching films can help me relax.",
    topic: "hobbies",
    category: "Types",
    level: "Beginner"
  },
  {
    id: "sports-hobbies-3",
    word: "playing sports (swimming, tennis, table tennis, football, go jogging)",
    phonetic: "",
    meaning_en: "engaging in physical games",
    meaning_vi: "chơi thể thao (bơi lội, quần vợt, bóng bàn, bóng đá, chạy bộ)",
    example_en: "Playing sports like football and swimming keeps me fit.",
    example_vi: "Chơi các môn thể thao như ném bóng và bơi lội giúp tôi giữ dáng.",
    usage_vi: "Liệt kê các môn thể thao. (Lưu ý: 'go jogging', không dùng 'play jogging').",
    speaking_sentence: "I am a big fan of playing sports, especially swimming and football.",
    topic: "hobbies",
    category: "Types",
    level: "Intermediate"
  },
  {
    id: "go-shopping-4",
    word: "go shopping",
    phonetic: "",
    meaning_en: "the activity of buying goods",
    meaning_vi: "đi mua sắm",
    example_en: "On weekends, I go shopping with my family in the mall.",
    example_vi: "Vào cuối tuần, tôi đi mua sắm cùng gia đình ở trung tâm thương mại.",
    usage_vi: "Động từ 'go' + V-ing (shopping).",
    speaking_sentence: "Sometimes, I also go shopping with my close friends.",
    topic: "hobbies",
    category: "Types",
    level: "Beginner"
  },
  {
    id: "bring-happiness-relax-5",
    word: "bring happiness to me and my family / make me relaxed, feel much happier",
    phonetic: "",
    meaning_en: "give joy and comfort",
    meaning_vi: "mang lại hạnh phúc cho tôi và gia đình / giúp tôi thư giãn, cảm thấy hạnh phúc hơn",
    example_en: "Playing board games can bring happiness to me and my family.",
    example_vi: "Chơi cờ bàn mang lại hạnh phúc cho tôi và gia đình.",
    usage_vi: "Có thể nói 'It makes me relaxed'.",
    speaking_sentence: "Firstly, taking up a new hobby can confidently make me relaxed and feel much happier.",
    topic: "hobbies",
    category: "Advantages",
    level: "Intermediate"
  },
  {
    id: "share-joy-6",
    word: "talk and share the joy with others",
    phonetic: "",
    meaning_en: "communicate and divide happiness",
    meaning_vi: "nói chuyện và chia sẻ niềm vui với người khác",
    example_en: "When we play together, we can talk and share the joy with others.",
    example_vi: "Khi chúng ta cùng chơi, ta có thể trò chuyện và chia sẻ niềm vui với những người khác.",
    usage_vi: "Cấu trúc Share + something + with somebody.",
    speaking_sentence: "Another benefit is that I can talk and share the joy with others.",
    topic: "hobbies",
    category: "Advantages",
    level: "Intermediate"
  },
  {
    id: "reduce-stress-7",
    word: "reduce the stress of everyday hard work and study",
    phonetic: "",
    meaning_en: "lower the pressure from daily tasks",
    meaning_vi: "giảm bớt căng thẳng của công việc và học tập khó nhọc hàng ngày",
    example_en: "Painting helps me reduce the stress of everyday hard work.",
    example_vi: "Vẽ tranh giúp tôi giảm được phần nào căng thẳng từ công việc vất vả hàng ngày.",
    usage_vi: "'reduce the stress of...'",
    speaking_sentence: "This activity allows me to reduce the stress of everyday hard work and study.",
    topic: "hobbies",
    category: "Advantages",
    level: "Intermediate"
  },
  {
    id: "develop-imagination-8",
    word: "develop imagination and creativity",
    phonetic: "",
    meaning_en: "improve the ability to create ideas",
    meaning_vi: "phát triển trí tưởng tượng và sự sáng tạo",
    example_en: "Reading books can really develop imagination and creativity.",
    example_vi: "Đọc sách có thể thực sự phát triển trí óc bay bổng và sự sáng tạo.",
    usage_vi: "Hai danh từ trừu tượng 'imagination' và 'creativity'.",
    speaking_sentence: "Furthermore, children can efficiently develop their imagination and creativity.",
    topic: "hobbies",
    category: "Advantages",
    level: "Intermediate"
  },
  {
    id: "broaden-knowledge-9",
    word: "broaden the knowledge / develop the cognitive skills",
    phonetic: "",
    meaning_en: "widen understanding and brain function",
    meaning_vi: "mở rộng kiến thức / phát triển các kỹ năng nhận thức",
    example_en: "Playing chess is a great way to develop the cognitive skills.",
    example_vi: "Chơi cờ là một cách hay để phát triển tư duy.",
    usage_vi: "Cognitive skills (kỹ năng tư duy/nhận thức) rất mạnh cho trình độ B2.",
    speaking_sentence: "Most importantly, reading books helps me broaden the knowledge.",
    topic: "hobbies",
    category: "Advantages",
    level: "Advanced"
  },
  {
    id: "games-violence-10",
    word: "Games contain a great deal of violence -> Increase aggressive feelings, thoughts and behaviors.",
    phonetic: "",
    meaning_en: "violent games make players more hostile",
    meaning_vi: "Trò chơi điện tử chứa nhiều yếu tố bạo lực -> Làm tăng cảm xúc, suy nghĩ và hành vi hung hăng.",
    example_en: "Because games contain a great deal of violence, they increase aggressive behaviors in kids.",
    example_vi: "Vì những trò chơi chứa nhiều bạo lực, chúng gây tăng tính hung hăng ở trẻ em.",
    usage_vi: "Cụm danh từ 'a great deal of violence'. Từ 'aggressive' (hung hăng).",
    speaking_sentence: "Unfortunately, some games contain a great deal of violence which increases aggressive behaviors.",
    topic: "hobbies",
    category: "Disadvantages",
    level: "Advanced"
  },
  {
    id: "not-focus-duties-11",
    word: "Not focus on their duties and study -> perform worse and worse at school",
    phonetic: "",
    meaning_en: "ignore responsibilities leading to bad grades",
    meaning_vi: "không tập trung vào bổn phận và học tập -> kết quả trên trường ngày càng sa sút",
    example_en: "Addicted gamers do not focus on their study, so they perform worse and worse.",
    example_vi: "Những game thủ nghiện game không tập trung vào việc học, nên học sinh thực hiện rất tệ.",
    usage_vi: "So sánh kép 'worse and worse' (càng ngày càng tệ).",
    speaking_sentence: "If youngsters play too much, they will perform worse and worse at school.",
    topic: "hobbies",
    category: "Disadvantages",
    level: "Intermediate"
  },
  {
    id: "suitable-games-limits-12",
    word: "choose suitable computer games / be not allowed to play violent games / set limits on the length of time",
    phonetic: "",
    meaning_en: "manage play time and content",
    meaning_vi: "chọn trò chơi phù hợp / không được phép chơi game bạo lực / đặt giới hạn thời gian chơi game",
    example_en: "Parents should set limits on the length of time for playing games.",
    example_vi: "Phụ huynh nên thiết lập ranh giới về thời lượng chơi đùa điện tử.",
    usage_vi: "Đây là các Giải pháp (Solutions) đưa ra trong Speaking Part 3 hoặc Writing.",
    speaking_sentence: "To solve this, parents must set strict limits on the length of time their children play games.",
    topic: "hobbies",
    category: "Solutions",
    level: "Intermediate"
  },

  // JOB / STUDY
  {
    id: "intro-study-work-1",
    word: "I am a third-year student at the university of... / I work as an accountant for ABC company",
    phonetic: "",
    meaning_en: "My current academic or professional status",
    meaning_vi: "Tôi là sinh viên năm ba của trường... / Tôi làm kế toán cho công ty ABC",
    example_en: "I work as an accountant for ABC company in the city center.",
    example_vi: "Tôi làm kế toán cho một công ty tại trung tâm.",
    usage_vi: "Cấu trúc giới thiệu bản thân thông dụng trong Speaking Part 1.",
    speaking_sentence: "I am a third-year student at the university of Economics in my hometown.",
    topic: "job_study",
    category: "Introduction",
    level: "Beginner"
  },
  {
    id: "study-duties-2",
    word: "do homework, make presentations, join clubs, do part-time jobs at the weekends",
    phonetic: "",
    meaning_en: "tasks normally done by students",
    meaning_vi: "làm bài tập về nhà, thuyết trình, tham gia câu lạc bộ, làm việc bán thời gian cuối tuần",
    example_en: "As a student, I have to make presentations and do part-time jobs.",
    example_vi: "Với tư cách sinh viên, tôi phải làm các bài thuyết trình và làm việc cuối tuần.",
    usage_vi: "Các động từ đi liền với danh từ (collocations): MAKE presentations, DO homework.",
    speaking_sentence: "My daily duties are doing homework and making presentations in class.",
    topic: "job_study",
    category: "Duties",
    level: "Intermediate"
  },
  {
    id: "in-charge-of-working-3",
    word: "I am in charge of... -> working with clients, solving clients' problems, contacting partners",
    phonetic: "",
    meaning_en: "I am responsible for customer relations",
    meaning_vi: "tôi chịu trách nhiệm... -> làm việc với khách hàng, giải quyết vấn đề của khách, liên hệ với đối tác",
    example_en: "In my company, I am in charge of solving clients' problems.",
    example_vi: "Ở công ty, tôi phụ trách hướng dẫn xử lý vấn đề của khách.",
    usage_vi: "Cấu trúc 'be in charge of + V-ing/N' cực kỳ ghi điểm trong công việc.",
    speaking_sentence: "Currently, I am in charge of working directly with our new clients.",
    topic: "job_study",
    category: "Duties",
    level: "Intermediate"
  },
  {
    id: "collaborate-smoothly-4",
    word: "collaborate with other departments to run the business smoothly",
    phonetic: "",
    meaning_en: "work well with other teams in the company",
    meaning_vi: "hợp tác với các phòng ban khác để điều hành công việc suôn sẻ",
    example_en: "Managers must collaborate with other departments to run the business smoothly.",
    example_vi: "Các quản lý phải cộng tác với các bộ phận khác để kinh doanh hiệu quả.",
    usage_vi: "Collaborate (hợp tác) + with. Run the business smoothly (vận hành suôn sẻ).",
    speaking_sentence: "Also, I must collaborate with other departments to run the business smoothly.",
    topic: "job_study",
    category: "Duties",
    level: "Advanced"
  },
  {
    id: "apply-knowledge-5",
    word: "apply the knowledge and skills of field I studied in my work",
    phonetic: "",
    meaning_en: "put into practice what I learned",
    meaning_vi: "áp dụng kiến thức và kỹ năng của lĩnh vực tôi đã học vào công việc",
    example_en: "My job allows me to apply the knowledge of my field.",
    example_vi: "Công việc cho phép tôi áp dụng kỹ năng ngành tôi học.",
    usage_vi: "Lý do vì sao mình yêu thích công việc hiện tại (Like).",
    speaking_sentence: "I love this job because I can actually apply the knowledge and skills I studied.",
    topic: "job_study",
    category: "Opinion",
    level: "Intermediate"
  },
  {
    id: "environment-develop-skills-6",
    word: "have an environment to develop skills / have opportunities for promotion",
    phonetic: "",
    meaning_en: "have a workplace that helps me improve and climb the ladder",
    meaning_vi: "có một môi trường để phát triển kỹ năng / có cơ hội thăng tiến",
    example_en: "A good job must have opportunities for promotion.",
    example_vi: "Một công việc tốt phải có các cơ hội được lên chức.",
    usage_vi: "Cụm danh từ 'opportunities for promotion' rất chuẩn (Promotion).",
    speaking_sentence: "Furthermore, the company gives me an environment to develop skills.",
    topic: "job_study",
    category: "Opinion",
    level: "Intermediate"
  },
  {
    id: "friendly-coworkers-7",
    word: "Co-workers are friendly and supportive",
    phonetic: "",
    meaning_en: "colleagues are kind and helpful",
    meaning_vi: "đồng nghiệp rất thân thiện và hay giúp đỡ",
    example_en: "I'm happy because my co-workers are friendly and supportive.",
    example_vi: "Tôi rất vui khi các đồng nghiệp của mình rất hiền hòa.",
    usage_vi: "Supportive (tính từ của support).",
    speaking_sentence: "Most importantly, my co-workers are very friendly and supportive when I need help.",
    topic: "job_study",
    category: "Opinion",
    level: "Beginner"
  },
  {
    id: "work-overtime-8",
    word: "sometimes, I have to work overtime -> have less time for family and friends",
    phonetic: "",
    meaning_en: "I work late hours so I don't see my family much",
    meaning_vi: "thỉnh thoảng, tôi phải làm thêm giờ -> có ít thời gian dành cho gia đình và bạn bè hơn",
    example_en: "Because I have to work overtime, I have less time for family.",
    example_vi: "Bởi vì tôi làm ngoài giờ, tôi có rất ít thì giờ bên nhà.",
    usage_vi: "Động từ 'work overtime' (làm thêm giờ).",
    speaking_sentence: "However, sometimes I have to work overtime, thus I have less time for my family.",
    topic: "job_study",
    category: "Opinion",
    level: "Intermediate"
  },
  {
    id: "far-from-home-9",
    word: "the company is far from home / the workload is huge -> feel tired/ overloaded",
    phonetic: "",
    meaning_en: "workplace is distant / I have too much work -> get exhausted",
    meaning_vi: "công ty xa nhà / khối lượng công việc khổng lồ -> cảm thấy mệt mỏi/ quá tải",
    example_en: "Since the workload is huge, I often feel overloaded.",
    example_vi: "Bởi vì khối lượng chuyên môn lớn, tôi thấy rất kiệt sức.",
    usage_vi: "Workload (khối lượng công việc). Overloaded (quá tải).",
    speaking_sentence: "My only dislike is that the workload is huge, which makes me feel somewhat overloaded.",
    topic: "job_study",
    category: "Opinion",
    level: "Intermediate"
  }
];

fs.writeFileSync("new_vocab.json", JSON.stringify(newVocab, null, 2));
console.log("Written " + newVocab.length + " items to new_vocab.json");
